
export const SITES = [
  {
    page: 'https://zjrb.zjol.com.cn/',
    site: 'head title',
    out_date: '.main-ednav-date',
    list: '.main-ed-articlenav-list li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://xh.xhby.net/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://paper.dzwww.com/dzrb/content/PageArticleIndex.htm',
    site: 'head title',
    out_date: '.B1[width=50%]',
    list: '#partTitleDiv1 td.td_line',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://hbrb.hebnews.cn/pc/paper/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://epaper.sxrb.com/index.shtml',
    site: 'head title',
    out_date: '.today',
    list: '.conMItemList li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://esb.sxdaily.com.cn/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.bmdh_con a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://szb.nxrb.cn/nxrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://szb.gansudaily.com.cn/gsrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://epaper.tibet3.com/qhrb/',
    site: 'head title',
    out_date: '.date',
    list: '.artile-list li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://lasa-eveningnews.com.cn/lsrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://xjrb.ts.cn/pindex?pName=xjrb',
    site: 'head title',
    list: '#articel_content li',
    title: 'a',
    url: 'a',
    href: 'url',
  },
  {
    page: 'https://szb.northnews.cn/nmgrb/paperindex.htm',
    site: 'head title',
    out_date: '#banner_top_date',
    list: '#main-ed-articlenav-list .default',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://epaper.lnd.com.cn/lnrbepaper/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://jlrbszb.dajilin.com/pc/paper/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://epaper.hljnews.cn/hljrb/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  // {
  //   page: 'http://paper.people.com.cn/rmrb/paperindex.htm',
  //   site: 'head title',
  //   out_date: '.date',
  //   list: '.news-list li',
  //   title: 'a',
  //   url: 'a',
  // },
  // {
  //   page: 'https://bjrbdzb.bjd.com.cn/bjrb/paperindex.htm',
  //   site: 'head title',
  //   list: '.nav-list-group li',
  //   title: 'a',
  //   url: 'a',
  //   href: 'data-href',
  //   name: '北京日报',
  // },
  // {
  //   page: 'http://epaper.tianjinwe.com/tjrb/',
  //   site: 'head title',
  //   out_date: 'span.default strong',
  //   list: 'div#btdh td.black',
  //   title: 'a',
  //   url: 'a',
  // },
  // {
  //   page: 'https://paper.xinmin.cn/index/xmwb/index.html',
  //   site: 'head title',
  //   out_date: '.dzb-date-wrap',
  //   list: '.dzb-enter-nav-benban-wrap a',
  //   name: '新民晚报'
  // },
  // {
  //   page: 'https://app.cqrb.cn/www/cqnews/index.html',
  //   site: 'head title',
  //   list: 'div#newslist h3.mxzxItem',
  //   date: 'span',
  //   title: 'a',
  //   url: 'a',
  // },
]
