
export const SITES = [
  {
    page: 'https://fjrb.fjdaily.com/pc/col/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#main-ed-articlenav-list .default',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://epaper.jxnews.com.cn/jxrb/',
    site: 'head title',
    out_date: 'td.default strong',
    list: 'table table table:nth-child(3) td.default:odd',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://epaper.southcn.com/nfdaily/html/index.html',
    site: 'head title',
    out_date: '.today',
    list: '#artPList1 li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://ssw.gxrb.com.cn/json/interface/epaper/api.php?name=gxrb',
    site: 'head title',
    out_date: '.m-nav .l1',
    list: 'dl#001 h3',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://epaper.voc.com.cn/hnrb/paperindex.htm',
    site: 'head title',
    out_date: 'span.default',
    list: '.ul02_l li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://hnrb.hinews.cn/paperindex.htm',
    site: 'head title',
    out_date: 'span.default',
    list: 'div[id^=content]',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://szb.gzrbs.com.cn/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://yndaily.yunnan.cn/',
    site: 'head title',
    out_date: '#paperdate',
    list: '#main-ed-articlenav-list .default',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://epaper.scdaily.cn/',
    site: 'head title',
    list: '.main_r ul:nth-child(3) p',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://epaper.hubeidaily.net/pc/column/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://newpaper.dahe.cn/hnrb/paperindex.htm',
    site: 'head title',
    out_date: 'div.dSearch strong',
    list: '.dNav + table td.default:odd',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://szb.ahnews.com.cn/ahrb/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://zjrb.zjol.com.cn/',
    site: 'head title',
    out_date: '.main-ednav-date',
    list: '.main-ed-articlenav-list li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://xh.xhby.net/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://paper.dzwww.com/dzrb/content/PageArticleIndex.htm',
    site: 'head title',
    out_date: '.B1[width=50%]',
    list: '#partTitleDiv1 td.td_line',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://hbrb.hebnews.cn/pc/paper/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://epaper.sxrb.com/index.shtml',
    site: 'head title',
    out_date: '.today',
    list: '.conMItemList li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://esb.sxdaily.com.cn/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.bmdh_con a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://szb.nxrb.cn/nxrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://szb.gansudaily.com.cn/gsrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '.news-list li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://epaper.tibet3.com/qhrb/',
    site: 'head title',
    out_date: '.date',
    list: '.artile-list li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'http://lasa-eveningnews.com.cn/lsrb/pc/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'https://xjrb.ts.cn/pindex?pName=xjrb',
    site: 'head title',
    list: '#articel_content li',
    title: 'a',
    url: 'a',
    href: 'url',
  },
  {
    page: 'https://szb.northnews.cn/nmgrb/paperindex.htm',
    site: 'head title',
    out_date: '#banner_top_date',
    list: '#main-ed-articlenav-list .default',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://epaper.lnd.com.cn/lnrbepaper/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://jlrbszb.dajilin.com/pc/paper/layout/index.html',
    site: 'head title',
    out_date: '#paperdate',
    list: '#articlelist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://epaper.hljnews.cn/hljrb/pc/layout/index.html',
    site: 'head title',
    out_date: '.newstime',
    list: '.newslist li',
    title: 'a',
    url: 'a',
    deep_page: '#list li:first a'
  },
  {
    page: 'http://paper.people.com.cn/rmrb/paperindex.htm',
    site: 'head title',
    out_date: '.date',
    list: '.news-list li',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://bjrbdzb.bjd.com.cn/bjrb/paperindex.htm',
    site: 'head title',
    list: '.nav-list-group li',
    title: 'a',
    url: 'a',
    href: 'data-href',
    name: '北京日报',
  },
  {
    page: 'http://epaper.tianjinwe.com/tjrb/',
    site: 'head title',
    out_date: 'span.default strong',
    list: 'div#btdh td.black',
    title: 'a',
    url: 'a',
  },
  {
    page: 'https://paper.xinmin.cn/index/xmwb/index.html',
    site: 'head title',
    out_date: '.dzb-date-wrap',
    list: '.dzb-enter-nav-benban-wrap a',
    name: '新民晚报'
  },
  {
    page: 'https://epaper.cqrb.cn/cqrb/',
    site: 'head title',
    out_date: 'td.default strong',
    list: 'table#001 td:odd',
    title: 'a',
    url: 'a',
  },
]

console.log(SITES.length)
